In [ ]:
# Лабораторна робота №1 — Варіант 19
# Виконав: Трощ Олег


In [1]:
# Завдання 1. Вектор добутків парних чисел на попередні непарні
import numpy as np

even = np.arange(2, 24, 2)
odd = even - 1
vec = even * odd
vec

array([  2,  12,  30,  56,  90, 132, 182, 240, 306, 380, 462])

In [2]:
# Завдання 2. Матриця 3×3 зі значень квадратів випадкових чисел 1–100
mat2 = np.random.randint(1, 101, (3, 3))
mat2_sq = mat2 ** 2
mat2_sq

array([[3249, 3025,  676],
       [2704,  169,  841],
       [2209, 5476, 5041]])

In [3]:
# Завдання 3. Матриця 5×5 з випадковими числами –2..2, середнє за модулем
mat3 = np.random.uniform(-2, 2, (5, 5))
avg_abs = np.abs(mat3).mean()
avg_abs

np.float64(0.9118723839909806)

In [4]:
# Завдання 4. Матриця 5×5 –5..5, середнє значення рядків
mat4 = np.random.uniform(-5, 5, (5, 5))
row_means = mat4.mean(axis=1)
row_means

array([ 0.05381883,  0.04705783, -2.02607503, -1.39241827,  0.08393155])

In [5]:
# Завдання 5. Два вектори по 7 елементів –10..10, вектор різниць
v1 = np.random.uniform(-10, 10, 7)
v2 = np.random.uniform(-10, 10, 7)
diff = v1 - v2
diff

array([  3.77077461,   1.21056393, -14.02237987,  -1.18871458,
         6.23623357,  -9.00365566, -10.49457235])

In [6]:
# Завдання 6. Добуток двох матриць 4×4 з цілих 7..17
M1 = np.random.randint(7, 18, (4, 4))
M2 = np.random.randint(7, 18, (4, 4))
prod_M = M1 @ M2
prod_M

array([[525, 629, 567, 665],
       [392, 491, 414, 495],
       [548, 670, 598, 600],
       [495, 617, 539, 591]])

In [7]:
# Завдання 7. Добуток матриць 4×2 та 2×5 з цілих –5..5
A = np.random.randint(-5, 6, (4, 2))
B = np.random.randint(-5, 6, (2, 5))
res = A @ B
res

array([[  5,  20,  15,   0, -35],
       [  7,  18,  17,  -2, -27],
       [  1,  -1,   1,  -1,   4],
       [ -5, -20, -15,   0,  35]])

In [8]:
# Завдання 8. Сума елементів побічної діагоналі матриці 2×2
X = np.random.randint(-10, 11, (2, 2))
secondary_diag_sum = X[0,1] + X[1,0]
secondary_diag_sum

np.int64(-2)

In [9]:
# Завдання 9. Найбільший елемент матриці 3×3 (дійсні –3..3)
mat9 = np.random.uniform(-3, 3, (3, 3))
max_elem = mat9.max()
max_elem

np.float64(2.4494722574269536)

In [10]:
# Завдання 10. Добуток матриці 3×4 і вектора 4×1
mat10 = np.random.randint(-5, 6, (3, 4))
vec10 = np.random.randint(1, 6, (4, 1))
res10 = mat10 @ vec10
res10

array([[-15],
       [-56],
       [-24]])

In [11]:
# Завдання 11. Добуток матриці 2×3 і вектора 3×1
mat11 = np.random.randint(-5, 6, (2, 3))
vec11 = np.random.randint(1, 6, (3, 1))
res11 = mat11 @ vec11
res11

array([[ 22],
       [-29]])

**Висновок:**

У ході виконання лабораторної роботи були створені одновимірні та двовимірні масиви різних розмірів, заповнені випадковими як цілими, так і дійсними числами. Для кожного завдання виконано необхідні обчислення: знаходження добутків, середніх значень, максимальних елементів, сум діагоналей та добутків матриць. Усі операції здійснено з використанням можливостей бібліотеки NumPy, що дало змогу ефективно опрацьовувати дані та виконувати математичні обчислення.