# Лабораторна робота: Операції з NumPy 1.2


## 1. Формування вектора з натуральних чисел

In [1]:
import numpy as np
vec = np.arange(1, 6)
vec


array([1, 2, 3, 4, 5])

## 2. Транспонування вектора

In [2]:
row_vec = np.matrix([1,2,3,4,5])
row_vec.T


matrix([[1],
        [2],
        [3],
        [4],
        [5]])

## 3. Розворот вектора

In [3]:
arr = np.array([1,2,3,4,5])
arr[::-1]


array([5, 4, 3, 2, 1])

## 4. Середнє значення

In [4]:
np.mean(arr)


np.float64(3.0)

## 5. Мін/макс елементи

In [5]:
arr.min(), arr.max()


(np.int64(1), np.int64(5))

## 6. Скалярний добуток

In [6]:
a = np.array([1,2,3])
b = np.array([3,4,5])
np.dot(a,b)


np.int64(26)

## 7. Нормалізація вектора

In [7]:
vec2 = np.array([2,4,6,8])
vec2 / np.linalg.norm(vec2)


array([0.18257419, 0.36514837, 0.54772256, 0.73029674])

## 8. Ортогональність векторів

In [8]:
x = np.array([0,1,0])
y = np.array([1,0,0])
np.dot(x,y)


np.int64(0)

## 9. Унікальні значення

In [9]:
mixed = np.array([1,1,2,3,3,4])
np.unique(mixed)


array([1, 2, 3, 4])

## 10. Арифметика з векторами

In [10]:
p = np.array([1,3,5])
q = np.array([2,4,6])
p+q, p-q, p*q, p/q


(array([ 3,  7, 11]),
 array([-1, -1, -1]),
 array([ 2, 12, 30]),
 array([0.5       , 0.75      , 0.83333333]))

## 11. Перевірка довжини вектора

In [11]:
test_vec = np.array([1,2,3,4,5])
np.isclose(np.linalg.norm(test_vec), 5)


np.False_

## 12. Матриця випадкових чисел

In [12]:
m = np.random.randint(0,10,(3,3))
m


array([[2, 2, 4],
       [4, 4, 6],
       [1, 5, 0]])

## 13. Визначник

In [13]:
np.linalg.det(m)


np.float64(15.999999999999998)

## 14. Обернена матриця

In [14]:
np.linalg.inv(m)


array([[-1.875,  1.25 , -0.25 ],
       [ 0.375, -0.25 ,  0.25 ],
       [ 1.   , -0.5  ,  0.   ]])

## 15. Розв'язання системи рівнянь

In [15]:
A = np.array([[2,1,-3],[1,3,2],[3,-1,1]])
b = np.array([5,8,2])
np.linalg.solve(A,b)


array([ 1.40000000e+00,  2.20000000e+00, -1.97372982e-16])

## 16. Множення матриць

In [16]:
M1 = np.matrix([[2,0,-1],[1,3,4]])
M2 = np.matrix([[1,2],[3,1],[-2,0]])
M1 @ M2


matrix([[4, 4],
        [2, 5]])

## 17. Транспонування матриці

In [17]:
M1.T


matrix([[ 2,  1],
        [ 0,  3],
        [-1,  4]])

## 18. Симетричність матриці

In [19]:
sym = np.array([[4,1,1],[1,4,1],[1,1,4]])
np.allclose(sym, sym.T)


True

## 19. Слід матриці

In [20]:
np.trace(sym)


np.int64(12)

## 20. Операції над матрицями

In [21]:
K = np.array([[1,2],[3,5]])
L = np.array([[2,1],[4,0]])
K+L, K-L, K*L


(array([[3, 3],
        [7, 5]]),
 array([[-1,  1],
        [-1,  5]]),
 array([[ 2,  2],
        [12,  0]]))

## 21. Матриця у степені

In [22]:
np.linalg.matrix_power(K,3)


array([[ 43,  74],
       [111, 191]])

## 22. Сортування матриці

In [23]:
T = np.array([[9,2,5],[1,3,7],[6,4,8]])
np.sort(T, axis=0), np.sort(T, axis=1)


(array([[1, 2, 5],
        [6, 3, 7],
        [9, 4, 8]]),
 array([[2, 5, 9],
        [1, 3, 7],
        [4, 6, 8]]))

## 23. Суми рядків

In [24]:
T = np.array([[2,4],[1,6]])
T.sum(axis=1).reshape(-1,1)


array([[6],
       [7]])

## **Висновок:** У підсумку виконання лабораторної роботи було опановано базові прийоми опрацювання масивів, векторів і матриць у Python за допомогою бібліотеки NumPy. Закріплено навички виконання лінійних, статистичних та алгебраїчних операцій, а також роботу з випадковими даними та системами рівнянь.